ALTER TABLE events   ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE teams    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE athletes ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
